# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InputURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('problem_content', models.TextField()),
                ('nick', models.CharField(blank=True, max_length=100)),
                ('problem_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('source_file', models.FileField(upload_to=b'originals/source')),
                ('input_file', models.FileField(upload_to=b'originals/input')),
                ('validator', models.FileField(upload_to=b'validators/')),
                ('penalty_per_line', models.IntegerField(default=2)),
                ('points', models.IntegerField(default=100)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbncc.Contest')),
                ('source_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('output_file', models.FileField(upload_to=b'submissions/output')),
                ('source_file', models.FileField(upload_to=b'submissions/source')),
                ('evaluation_result', models.CharField(default='0', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('time_penalty', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbncc.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
