# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test',
            field=models.IntegerField(default=100),
        ),
    ]
