# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='source_author',
            field=models.ForeignKey(default='server', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
