# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
