# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0002_problem_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test',
        ),
    ]
