# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0002_problem_problem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='source_filename',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
