# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0003_remove_problem_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='phase',
            field=models.IntegerField(null=True),
        ),
    ]
