# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0004_contest_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='phase',
            field=models.IntegerField(choices=[('Phase 1', 1), ('Phase 2', 2)], default=2),
            preserve_default=False,
        ),
    ]
