# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='f',
            field=models.FileField(default='a', upload_to='submissions/'),
            preserve_default=False,
        ),
    ]
