# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0004_problem_source_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='input_file_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='source_author',
            field=models.CharField(default='server', max_length=100),
        ),
    ]
