# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0005_test_f'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_file_name',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='source_filename',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='output_filename',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='source_filename',
        ),
        migrations.AddField(
            model_name='problem',
            name='input_file',
            field=models.FileField(default='a', upload_to=b'/media/originals/input'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='source_file',
            field=models.FileField(default='a', upload_to=b'/media/originals/source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='output_file',
            field=models.FileField(default='a', upload_to=b'/media/submissions/output'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='source_file',
            field=models.FileField(default='a', upload_to=b'/media/submissions/source'),
            preserve_default=False,
        ),
    ]
