# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0005_auto_20170216_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='nick',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
