# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0005_auto_20170301_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='phase',
            field=models.IntegerField(choices=[(1, 'Phase 1'), (2, 'Phase 2')]),
        ),
    ]
