# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0006_problem_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input_file_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='nick',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
