# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0006_auto_20170228_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='validator',
            field=models.FileField(upload_to=b'/media/validators'),
        ),
    ]
