# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0007_auto_20170228_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='penalty_per_line',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(choices=[('50', 50), ('100', 100), ('150', 150), ('200', 200), ('250', 250), ('400', 400), ('500', 500)], default=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='output_file',
            field=models.FileField(upload_to=b'submissions/output'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='source_file',
            field=models.FileField(upload_to=b'submissions/source'),
        ),
    ]
