# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0009_submission_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 17, 10, 12, 3, 618808)),
        ),
    ]
