# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0010_auto_20170228_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='penalty_per_line',
            field=models.IntegerField(default=2, verbose_name=(('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5))),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=100, verbose_name=(('50', 50), ('100', 100), ('150', 150), ('200', 200), ('250', 250), ('400', 400), ('500', 500))),
        ),
    ]
