# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0011_auto_20170228_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='penalty_per_line',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=2),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.IntegerField(choices=[('50', 50), ('100', 100), ('150', 150), ('200', 200), ('250', 250), ('400', 400), ('500', 500)], default=100),
        ),
    ]
