# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0011_auto_20170217_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
