# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0012_auto_20170217_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output_file_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='source_filename',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
