# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0013_auto_20170228_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input_file',
            field=models.FileField(upload_to=b'originals/input'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source_file',
            field=models.FileField(upload_to=b'originals/source'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='validator',
            field=models.FileField(upload_to=b'validators/'),
        ),
    ]
