# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0014_auto_20170228_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
