# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0014_auto_20170217_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submit_time',
            field=models.DateTimeField(),
        ),
    ]
