# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0016_auto_20170219_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
