# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncc', '0018_auto_20170220_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='validator',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
